name: "CI"
on: [push, pull_request]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: pip install wheel
    - run: pip install pipenv
    - run: pipenv install --dev --system --deploy --clear
    - run: python setup.py install
#    - run: pytest
